// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjOhDpRK25x-tb5d6dT2Gfnsi6AUHGNCs',
    appId: '1:559406782345:web:b63d294eaf0f2434c63358',
    messagingSenderId: '559406782345',
    projectId: 'budgetpro-a5d90',
    authDomain: 'budgetpro-a5d90.firebaseapp.com',
    storageBucket: 'budgetpro-a5d90.firebasestorage.app',
    measurementId: 'G-M90KB4GR1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjVetzhG2fd2-YQdoaibUhXvwQL4y9prA',
    appId: '1:559406782345:android:e2cdd58e4e642408c63358',
    messagingSenderId: '559406782345',
    projectId: 'budgetpro-a5d90',
    storageBucket: 'budgetpro-a5d90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEv9PQeWEMqvyBdnam3DgPnefO-l6-Gpc',
    appId: '1:559406782345:ios:640783012c59556ec63358',
    messagingSenderId: '559406782345',
    projectId: 'budgetpro-a5d90',
    storageBucket: 'budgetpro-a5d90.firebasestorage.app',
    iosBundleId: 'com.budgetpro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEv9PQeWEMqvyBdnam3DgPnefO-l6-Gpc',
    appId: '1:559406782345:ios:b2a6efb4ab1e40d2c63358',
    messagingSenderId: '559406782345',
    projectId: 'budgetpro-a5d90',
    storageBucket: 'budgetpro-a5d90.firebasestorage.app',
    iosBundleId: 'com.example.budgetPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjOhDpRK25x-tb5d6dT2Gfnsi6AUHGNCs',
    appId: '1:559406782345:web:a5fc07784d059feec63358',
    messagingSenderId: '559406782345',
    projectId: 'budgetpro-a5d90',
    authDomain: 'budgetpro-a5d90.firebaseapp.com',
    storageBucket: 'budgetpro-a5d90.firebasestorage.app',
    measurementId: 'G-C4VVQP0VK3',
  );
}
